version: '3.9'
services:
  evolution-api:
    image: atendai/evolution-api:latest
    restart: always
    # para Koyeb docker-compose recomendo usar a variável PORT, com fallback:
    ports:
      - "${PORT:-8080}:8080"
    env_file:
      - .env
    # se você usar Volumes Koyeb, monte em /evolution/instances
    volumes:
      - evolution_instances:/evolution/instances

volumes:
  evolution_instances:
