services:
  evolution-api:
    image: atendeai/evolution-api:latest
    restart: always
    ports:
      - "8080:8080" 
    environment:
      - API_KEY=${API_KEY} 
      - DATABASE_ENABLED=false
