services:
  evolution-api:
    image: atendai/evolution-api:latest
    restart: always
    ports:
      - "${PORT}:8080"
    environment:
      - AUTHENTICATION_API_KEY=${AUTHENTICATION_API_KEY}
      - SERVER_PORT=8080




